name: voola
description: TBCC Crypto Wallet

publish_to: 'none'

version: 2.1.1+83

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  intl_utils: ^2.6.1
  dartx: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.1.6
  qr_code_scanner: ^0.5.1
  qr_flutter: ^4.0.0
  http: ^0.13.3
  decimal: ^1.2.0
  get_it: ^7.1.3
  provider: ^6.0.2
  flutter_math_fork: ^0.6.2
  flutter_secure_storage: ^4.2.1
  local_auth: ^1.1.6
  path_provider: ^2.0.2
  url_launcher: ^6.0.6
  install_plugin:
    git: https://github.com/hui-z/flutter_install_plugin.git
  flutter_svg: ^1.0.0
  webview_flutter: ^2.0.12
  cached_network_image: ^3.0.0
  nfc_in_flutter:
    git: https://github.com/semlette/nfc_in_flutter.git ## nullsafe but not released to pub.dev yet

  quick_actions: ^0.6.0+2
  flutter_modular: ^3.2.2+1

  wallet_connect:
    git: https://github.com/Tbcc-wallet/wallet_connect_dart.git
  bip39: ^1.0.6
  web3dart: ^2.1.3
  binance_chain:
    git:
      url: https://github.com/Tbcc-wallet/binance_chain_dart.git
      ref: dev

  carousel_slider: ^4.0.0
  animated_theme_switcher: ^2.0.1
  shimmer: ^2.0.0
  fl_chart: ^0.36.3
  page_transition: ^2.0.2
  auto_size_text: ^3.0.0-nullsafety.0
  overlay_support: ^1.2.1
  rive: ^0.7.28
  stacked_services:
  pointycastle: 3.3.4
  animations: ^2.0.1
  share_plus: ^2.1.4
  solana:
  flutter_html: ^3.0.0-alpha.3
  flutter_displaymode: ^0.3.2
  showcaseview: ^1.1.2


dependency_overrides:
  platform: ^3.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/market/
    - assets/images/flags/
    - assets/images/vector/icons/
    - assets/images/vector/tokens/
    - assets/tokens/
  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost/Jost-Black.ttf
          weight: 900
        - asset: assets/fonts/Jost/Jost-Bold.ttf
          weight: 700
        - asset: assets/fonts/Jost/Jost-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Jost/Jost-Medium.ttf
          weight: 500
        - asset: assets/fonts/Jost/Jost-Regular.ttf
flutter_intl:
  enabled: true

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#438AF9"
  image: assets/images/splash.png
  android: true
  ios: true
  web: false
  fullscreen: true
